const speciesStatistics = {
    "Parlak Dikenli Kertenkele": {
      class: "Reptilia Luminis",
      description: "Bu tür, geceleri parlayan pullarıyla dikkat çeker. Işığa tepki veren derisiyle biyolüminesans araştırmalarında kullanılır.",
      image: "src/images/Parlak_Dikenli_Kertenkele.png",
      themeColor: "bg-gradient-to-r from-[#2ca0b0] to-[#992fbd]",
      fields: [
        { key: "totalPopulation", label: "Toplam Popülasyon" },
        { key: "totalAlivePopulation", label: "Toplam Canlı Popülasyon" },
        { key: "totalDeadPopulation", label: "Toplam Ölü Popülasyon" },
        { key: "totalMalePopulation", label: "Toplam Erkek Popülasyon" },
        { key: "totalFemalePopulation", label: "Toplam Dişi Popülasyon" },
        { key: "totalFertileFemalePopulation", label: "Toplam Doğurgan Dişi Popülasyon" },
        { key: "totalNewBornPopulation", label: "Toplam Yeni Doğan Popülasyon" },
        { key: "totalYoungPopulation", label: "Toplam Genç Popülasyon" },
        { key: "totalOldPopulation", label: "Toplam Yaşlı Popülasyon" },
        { key: "populationStatus", label: "Popülasyon Durumu" },
      ],
    },
    "Kelebek Kanatlı Anka": {
      class: "Mammalia Volantis",
      description: "Kanatları kelebek gibi zar yapıda olan bu anka türü, uçuş esnasında oluşan titreşimlerle iletişim kurar.",
      image: "src/images/Kelebek_Kanatlı_Anka.png",
      themeColor: "bg-gradient-to-r from-[#df59db] to-[#f29c4b]",
      fields: [
        { key: "totalPopulation", label: "Toplam Popülasyon" },
        { key: "totalAlivePopulation", label: "Toplam Canlı Popülasyon" },
        { key: "totalDeadPopulation", label: "Toplam Ölü Popülasyon" },
        { key: "totalMalePopulation", label: "Toplam Erkek Popülasyon" },
        { key: "totalFemalePopulation", label: "Toplam Dişi Popülasyon" },
        { key: "totalFertileFemalePopulation", label: "Toplam Doğurgan Dişi Popülasyon" },
        { key: "totalNewBornPopulation", label: "Toplam Yeni Doğan Popülasyon" },
        { key: "totalYoungPopulation", label: "Toplam Genç Popülasyon" },
        { key: "totalOldPopulation", label: "Toplam Yaşlı Popülasyon" },
        { key: "populationStatus", label: "Popülasyon Durumu" },
      ],
    },
    "Simli Mantar": {
      class: "Fungalia Intellecta",
      description: "Bilinçli mikorizal yapısıyla tanınır, fotosentez yapmamasına rağmen ışığa duyarlıdır.",
      image: "/src/images/Simli_Mantar.png",
      themeColor: "bg-gradient-to-r from-[#f351fa] to-[#0b13b6]",
      fields: [
        { key: "totalPopulation", label: "Toplam Popülasyon" },
        { key: "totalAlivePopulation", label: "Toplam Canlı Popülasyon" },
        { key: "totalDeadPopulation", label: "Toplam Ölü Popülasyon" },
        { key: "totalMalePopulation", label: "Toplam Erkek Popülasyon" },
        { key: "totalFemalePopulation", label: "Toplam Dişi Popülasyon" },
        { key: "totalFertileFemalePopulation", label: "Toplam Doğurgan Dişi Popülasyon" },
        { key: "totalNewBornPopulation", label: "Toplam Yeni Doğan Popülasyon" },
        { key: "totalYoungPopulation", label: "Toplam Genç Popülasyon" },
        { key: "totalOldPopulation", label: "Toplam Yaşlı Popülasyon" },
        { key: "populationStatus", label: "Popülasyon Durumu" },
      ],
    },
    "Fosforlu Göl Balığı": {
      class: "Pisces Photonica",
      description: "Fosforlu pigmentlerle kaplı cildiyle, göl derinliklerinde ışık saçar. Su kalitesi göstergesi olarak kullanılır.",
      image: "src/images/Fosforlu_Göl_Balığı.png",
      themeColor: "bg-gradient-to-r from-[#fe9e1d] to-[#1dfee2]",
      fields: [
        { key: "totalPopulation", label: "Toplam Popülasyon" },
        { key: "totalAlivePopulation", label: "Toplam Canlı Popülasyon" },
        { key: "totalDeadPopulation", label: "Toplam Ölü Popülasyon" },
        { key: "totalMalePopulation", label: "Toplam Erkek Popülasyon" },
        { key: "totalFemalePopulation", label: "Toplam Dişi Popülasyon" },
        { key: "totalFertileFemalePopulation", label: "Toplam Doğurgan Dişi Popülasyon" },
        { key: "totalNewBornPopulation", label: "Toplam Yeni Doğan Popülasyon" },
        { key: "totalYoungPopulation", label: "Toplam Genç Popülasyon" },
        { key: "totalOldPopulation", label: "Toplam Yaşlı Popülasyon" },
        { key: "populationStatus", label: "Popülasyon Durumu" },
      ],
    },
    "Buzul Semenderi": {
      class: "Amphibia Glacialis",
      description: "Aşırı soğuk ortamlarda hayatta kalma yeteneğiyle bilinir. Derisinden ışık yayar ve kas titreşimleriyle ısı üretir.",
      image: "src/images/Buzul_Semenderi.png",
      themeColor: "bg-gradient-to-r from-[#1d27fe] to-[#2027ff]",
      fields: [
        { key: "totalPopulation", label: "Toplam Popülasyon" },
        { key: "totalAlivePopulation", label: "Toplam Canlı Popülasyon" },
        { key: "totalDeadPopulation", label: "Toplam Ölü Popülasyon" },
        { key: "totalMalePopulation", label: "Toplam Erkek Popülasyon" },
        { key: "totalFemalePopulation", label: "Toplam Dişi Popülasyon" },
        { key: "totalFertileFemalePopulation", label: "Toplam Doğurgan Dişi Popülasyon" },
        { key: "totalNewBornPopulation", label: "Toplam Yeni Doğan Popülasyon" },
        { key: "totalYoungPopulation", label: "Toplam Genç Popülasyon" },
        { key: "totalOldPopulation", label: "Toplam Yaşlı Popülasyon" },
        { key: "populationStatus", label: "Popülasyon Durumu" },
      ],
    },
  };
  
  export default speciesStatistics;
  