const speciesModel = {
    "Parlak Dikenli Kertenkele": {
      class: "Reptilia Luminis",
      description: "Bu tür, geceleri parlayan pullarıyla dikkat çeker. Işığa tepki veren derisiyle biyolüminesans araştırmalarında kullanılır.",
      image: "src/images/Parlak_Dikenli_Kertenkele.png",
      themeColor: "bg-gradient-to-r from-[#2ca0b0] to-[#992fbd]",
      fields: [
        { key: "bioLuminescenceIntensity_cd_m2", label: "Biyo-ışık Yoğunluğu (cd/m²)" },
        { key: "scaleRegenerationDays", label: "Pul Rejenerasyon Süresi (gün)" },
        { key: "bloodOxygenSaturation_pct", label: "Oksijen Doygunluğu (%)" },
        { key: "coreTemperature_C", label: "Vücut Sıcaklığı (°C)" },
        { key: "lumitonin_ng_mL", label: "Lumitonin (ng/mL)" },
        { key: "plasmaElectrolytes_mmol_L_Na", label: "Na⁺ mmol/L" },
        { key: "plasmaElectrolytes_mmol_L_K", label: "K⁺ mmol/L" },
        { key: "plasmaElectrolytes_mmol_L_Ca", label: "Ca²⁺ mmol/L" },
      ],
    },
    "Kelebek Kanatlı Anka": {
      class: "Mammalia Volantis",
      description: "Kanatları kelebek gibi zar yapıda olan bu anka türü, uçuş esnasında oluşan titreşimlerle iletişim kurar.",
      image: "src/images/Kelebek_Kanatlı_Anka.png",
      themeColor: "bg-gradient-to-r from-[#df59db] to-[#f29c4b]",
      fields: [
        { key: "heartRate_BPM", label: "Kalp Atışı (BPM)" },
        { key: "bloodGlucose_mg_dL", label: "Kan Glukozu (mg/dL)" },
        { key: "respirationRate_bpm", label: "Solunum (nefes/dk)" },
        { key: "wingMembraneO2Permeability", label: "Kanat Zar. O₂ Geçirgenliği" },
        { key: "fecalParasites_present", label: "Parazit Var mı?" },
        { key: "fecalParasites_species", label: "Parazit Türü" },
        { key: "auditorySensitivity_Hz", label: "İşitme Frekansı (Hz)" },
      ],
    },
    "Simli Mantar": {
      class: "Fungalia Intellecta",
      description: "Bilinçli mikorizal yapısıyla tanınır, fotosentez yapmamasına rağmen ışığa duyarlıdır.",
      image: "/src/images/Simli_Mantar.png",
      themeColor: "bg-gradient-to-r from-[#f351fa] to-[#0b13b6]",
      fields: [
        { key: "myceliumDensity_g_cm3", label: "Misel Yoğunluğu" },
        { key: "lightAbsorptionRate_umol_m2_s", label: "Işık Emilimi (μmol/m²/s)" },
        { key: "soilPhOptimum_min", label: "Toprak pH Min" },
        { key: "soilPhOptimum_max", label: "Toprak pH Max" },
        { key: "symbioticEfficiency_pct", label: "Simbiyotik Verimlilik (%)" },
        { key: "nematodeInfectionCount", label: "Nematod Enf. Sayısı" },
        { key: "intracellularMoisture_pct", label: "İntraselüler Nem (%)" },
      ],
    },
    "Fosforlu Göl Balığı": {
      class: "Pisces Photonica",
      description: "Fosforlu pigmentlerle kaplı cildiyle, göl derinliklerinde ışık saçar. Su kalitesi göstergesi olarak kullanılır.",
      image: "src/images/Fosforlu_Göl_Balığı.png",
      themeColor: "bg-gradient-to-r from-[#fe9e1d] to-[#1dfee2]",
      fields: [
        { key: "gillFiltrationEfficiency_mg_L", label: "Solungaç Verimi (mg/L)" },
        { key: "skinPigmentIntensity_RGB_r", label: "Pigment Kırmızı (R)" },
        { key: "skinPigmentIntensity_RGB_g", label: "Pigment Yeşil (G)" },
        { key: "skinPigmentIntensity_RGB_b", label: "Pigment Mavi (B)" },
        { key: "waterTempTolerance_C_min", label: "Su Sıcaklık Min (°C)" },
        { key: "waterTempTolerance_C_max", label: "Su Sıcaklık Max (°C)" },
        { key: "ionBalance_mmol_L_Na", label: "Na⁺ mmol/L" },
        { key: "ionBalance_mmol_L_K", label: "K⁺ mmol/L" },
        { key: "ionBalance_mmol_L_Cl", label: "Cl⁻ mmol/L" },
        { key: "parasiteLoad_perSample", label: "Parazit Sayısı" },
        { key: "swimmingActivity_cm_s", label: "Yüzme Aktivitesi (cm/s)" },
      ],
    },
    "Buzul Semenderi": {
      class: "Amphibia Glacialis",
      description: "Aşırı soğuk ortamlarda hayatta kalma yeteneğiyle bilinir. Derisinden ışık yayar ve kas titreşimleriyle ısı üretir.",
      image: "src/images/Buzul_Semenderi.png",
      themeColor: "bg-gradient-to-r from-[#1d27fe] to-[#2027ff]",
      fields: [
        { key: "lightEmissionTemperature_C", label: "Işık Yayım Sıcaklığı (°C)" },
        { key: "skinPermeability_waterVapor", label: "Deri Geçirgenliği" },
        { key: "coreTempSetpoint_C", label: "Sıcaklık Sabiti (°C)" },
        { key: "muscleVibrationFreq_Cold_Hz", label: "Kas Titreşimi (Hz)" },
        { key: "subcutaneousMineralSaltRatio", label: "Mineral Tuz Oranı" },
        { key: "iceWaterSeparationTime_s", label: "Buz-Su Ayrım Süresi (s)" },
      ],
    },
  };
  
  export default speciesModel;
  